#!/bin/bash

# Шрифт заголовков окон
TitleFontNameXft="Inter:size=12"

# Шрифт главного меню (твое jgmenu может брать отсюда)
MenuFontNameXft="Inter:size=10"

# Шрифт на панели задач (кнопки окон)
TaskBarFontNameXft="Inter:size=10"

# Шрифт в области уведомлений (часы и т.д.)
StatusFontNameXft="Inter:size=10"

# Общий шрифт для списков и подсказок
QuickSwitchFontNameXft="Inter:size=12:bold"
NormalButtonFontNameXft="Inter:size=10"